# Generated by Django 4.2.2 on 2023-07-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='...')),
                ('time_reception', models.DateField(help_text='Выберите дату и время приема(Форма - 2023-01-01)')),
                ('user_doctor', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment', to='account_app.doctor')),
                ('user_patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment', to='account_app.patient')),
            ],
        ),
    ]
