# Generated by Django 4.2.2 on 2023-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_alter_appointment_user_doctor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('user_doctor', 'user_patient'), name='limit_appointment'),
        ),
    ]
