# Generated by Django 4.2.2 on 2023-07-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        ('content_app', '0003_appointment_limit_appointment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='limit_appointment',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('user_doctor', 'user_patient')},
        ),
    ]
