# Generated by Django 4.2.2 on 2023-07-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0006_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='click_bool',
            field=models.BooleanField(default=False),
        ),
    ]
